[build]
    publish = "build/"
    command = "make ci" 

[[redirects]]
    from = "/.well-known/webfinger"
    to = "https://h.icyphox.sh/.well-known/webfinger"
    force = true

[[redirects]]
    from = "/*"
    to = "/404"
    status = 404
